# fly.toml app configuration file generated for neon-latencies on 2023-12-15T14:58:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "neon-latencies"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
