alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: nqb-nyc-us-east-1
    match:
      path:
        prefix: /
name: nqb-nyc-us-east-1
region: nyc
services:
- envs:
  - key: NQB_DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: postgres://rest-of-the-connection-string
  - key: NQB_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: a-secure-api-key
  - key: NQB_DO_REGION
    scope: RUN_AND_BUILD_TIME
    value: nyc
  health_check:
    http_path: /health
  http_port: 3000
  image:
    registry: evanatneon
    registry_type: DOCKER_HUB
    repository: neon-query-bench
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: nqb-nyc-us-east-1
